# Generated by Django 5.0.6 on 2024-07-02 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watch',
            old_name='url',
            new_name='watch_url',
        ),
    ]
