version: 2
updates:
  - package-ecosystem: ""
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/apps/frontend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
