version: 2
updates:
  - package-ecosystem: "pip"
    directory: /
    schedule:
      interval: "daily"
      time: "07:00"
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    groups:
      dev-dependencies:
        dependency-type: "development"

  - package-ecosystem: "npm"
    directory: /apps/frontend
    schedule:
      interval: "daily"
      time: "07:00"
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    groups:
      vue:
        patterns:
          - "vue*"
          - "@vueuse/*"
          - "vee-validate"
          - "@vee-validate/*"
          - "yup"
          - "pinia*"
      tailwindcss:
        patterns:
          - "@tailwindcss/*"
          - "tailwindcss"
      dev-dependencies:
        dependency-type: "development"

  - package-ecosystem: "github-actions"
    directory: /
    schedule:
      interval: "weekly"
      day: "friday"
