version: 2
updates:
  - package-ecosystem: "pip"
    directory: /
    schedule:
      interval: "daily"
      time: "07:00"

  - package-ecosystem: "npm"
    directory: "/apps/frontend"
    schedule:
      interval: "daily"
      time: "07:00"
    allow:
      - dependency-type: "production"

  - package-ecosystem: "npm"
    directory: "/apps/frontend"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "development"

  - package-ecosystem: "github-actions"
    directory: /
    schedule:
      interval: "weekly"
