services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    network_mode: ""
    networks:
      - default
    depends_on:
      - db

  db:
    ports:
      - "5432:5432"

  maildev:
    ports:
      - "1025:1025"
    network_mode: ""
    networks:
      - default
