version: '3.4'

services:
  webdiff:
    image: webdiff
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - postgres

  postgres:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=webdiff
      - POSTGRES_USER=webdiff
      - POSTGRES_PASSWORD=webdiff

volumes:
  pgdata:
