services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: webdiff
      POSTGRES_DB: webdiff
      POSTGRES_PASSWORD: webdiff

  maildev:
    image: maildev/maildev
    environment:
      MAILDEV_IP: "::"
    network_mode: service:db

volumes:
  postgres-data:
